### ISSUE TITLE
Connect multiple timers at the same time

### ISSUE THREAD

**Issue by biencuong** [adrobinoga/pyzatt#3]
In your example you are connecting to a single IP address (for 1 machine), how do I connect multiple machines at once?

**Comment by adrobinoga** [comment]
Hi, there are two general ways to use the devices
1. To change settings in devices or read/modify data(attendance records, fingerprints, users, etc), this follows the general process connect-read/modify-disconnect. This can be done with one connection at a time.
2. Read realtime data from devices (a user opened the door, a user failed to log in, etc) , in this case a connection must be created to all the devices that you want to connect, and then you wait for events from that devices, you could use threads to read the incoming event, or you could simply use pooling, you can check this script [multiple_realtime.py](https://gist.github.com/adrobinoga/f7d2f5f0a4bc92f4c3c6fd18139374f2#file-multiple_realtime-py), hope it helps, please note that all the connections are terminated if one is terminated, but can be fixed with a little more programming

**Comment by biencuong** [comment]
Very good. thank you for the enthusiastic support!

**Comment by biencuong** [comment]
Traceback (most recent call last):
  File "multiple_realtime.py", line 36, in <module>
    for [ip_addr, z] in zk_dev:
ValueError: too many values to unpack (expected 2)

I have tested and encountered the above error.
And I see there seems to be some confusion at ip_addresses at lines 25, 28, 31 and ip_addr at line 36?
![ff06d6e5ef6a0f34567b](https://user-images.githubusercontent.com/26410999/48041227-dcd05500-e1ae-11e8-872c-aec7b7010483.jpg)

**Comment by adrobinoga** [comment]
That's a silly error, about how to iterate through a dictionary ([see this](https://stackoverflow.com/questions/3294889/iterating-over-dictionaries-using-for-loops)), sorry about that
It should be:
`
 for [ip_addr, z] in zk_dev.items():
`
Instead of 
`
for [ip_addr, z] in zk_dev:
`
I fixed all those for sentences in the previous gist example
Tell me if it works

**Comment by biencuong** [comment]
Yes. File "multiple_realtime.py", line 36 and 51.
for [ip_addr, z] in zk_dev: -> for [ip_addr, z] in zk_dev.items():

**Comment by biencuong** [comment]
ConnectionRefusedError: [Errno 111] Connection refused
Can you fix the error when 1 of the machines lose connection?

**Comment by adrobinoga** [comment]
It seems that the items method it is only a view object, changed the code again to use a list of tuples, try it

**Comment by biencuong** [comment]
> It seems that the items method it is only a view object, changed the code again to use a list of tuples, try it

thanks!
